version: 2.1

commands:
  install_dependencies:
    description: "Install dependencies"
    steps:
      - restore_cache:
          keys: yarn
      - run: |
          yarn install --frozen-lockfile --no-progress --cache-folder .yarn
          yarn ng --version
      - save_cache:
          key: yarn
          paths:
            - .yarn

jobs:
  lint:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - install_dependencies
      - run: yarn lint

  test:
    docker:
      - image: esanzgar:node-chromium
    steps:
      - checkout
      - install_dependencies
      - run: yarn test --progress=false --karma-config=src/karma_chromium.conf.js
      - store_artifacts:
          path:
            - coverage
  build:
    docker:
      # - image: esanzgar/node-chromium
      - image: node/chromium
    steps:
      - checkout
      - install_dependencies
      - run: yarn lint
      # - run: yarn test --progress=false --karma-config=src/karma_chromium.conf.js
      # - run: yarn build --progress=false
      - store_artifacts:
          path:
            # - coverage
            - dist/workout

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint
      - test
      - build:
          requires:
            - test
      #    filters:
      #      branches:
      #        ignore:
      #          - develop
      #          - /feature-.*/
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
